### ISSUE TITLE
multi domain wildcard certificate

### ISSUE THREAD

**Issue by NextBlaubeere** [nh2/internal-contstrained-pki#2]
It would be useful in some cases to have support for creating a multidomain certificate.
e.g. one certificate with `*.home.internal` and `*.home.lan` at the same time.

**Comment by nh2** [comment]
I'd probably leave that to local modification of the script.

The main script is currently intended mainly as an example of how to invoke `openssl`, not a full tool (for that I'd probably write it in a more robust language than `bash`).

**Comment by NextBlaubeere** [comment]
I see. 👍
